// lib/mock-data.ts
// Realistic mock data for frontend development before backend is ready

import { DiscoverResponse } from "./types";

export function mockDiscoverResponse(productName: string): DiscoverResponse {
  return {
    request_id: "mock-" + Date.now(),
    product_name: productName,
    enhanced_queries: [
      `${productName} app reddit`,
      "fitness dating community",
      "gym singles meetup",
      "workout partner dating app",
    ],
    subreddits: [
      {
        name: "r/fitness",
        display_name: "Fitness",
        relevance_score: 0.91,
        reasoning: [
          "High keyword overlap with gym/fitness terminology",
          "1.2M+ active users frequently discuss gym culture and social dynamics",
          "Multiple threads about meeting people at the gym indicate audience fit",
        ],
        subscribers: 1200000,
        active_users: 4500,
        rules_summary: [
          "No self-promotion outside weekly thread",
          "Flair required on all posts",
          "No link-only posts",
        ],
        community_tone: "supportive, advice-oriented, casual",
        recent_topics: ["workout splits", "gym etiquette", "progress pics", "gym anxiety"],
        post_drafts: [
          {
            type: "question_post",
            label: "Question Post",
            title: "Anyone else wish there was a better way to meet people who are into fitness?",
            body: "I've been going to my local gym for about 2 years now, and I've noticed that while I see the same people every day, there's no good way to actually connect with them outside the gym. Dating apps don't really let you filter for fitness lifestyle, and approaching people mid-workout feels awkward.\n\nRecently I stumbled across this new app that's specifically designed for gym-goers to connect. Has anyone else tried niche dating apps like this? I'm curious if the smaller user base actually leads to better matches since everyone already shares a common interest.",
            strategy: "Frames product discovery as a genuine personal experience, inviting community discussion. Matches r/fitness's advice-oriented tone.",
            confidence_score: 0.82,
            recommended_cadence: "Post on weekday evenings (6-9 PM EST) when gym-goers are most active. Avoid Monday mornings.",
          },
          {
            type: "discussion_post",
            label: "Discussion Post",
            title: "How do you actually meet people who share your fitness lifestyle?",
            body: "Serious question — I feel like fitness is such a core part of my identity, but it's surprisingly hard to find a partner who genuinely shares that. Regular dating apps don't really account for lifestyle compatibility beyond surface-level interests.\n\nFor those of you in relationships, how did you meet your partner? Did fitness play a role? And for those still looking, what's been your experience trying to find someone who actually gets the gym life?\n\nI'm curious because it seems like there's a real gap here that nobody's really solving well.",
            strategy: "Discussion question that surfaces the exact problem the product solves without mentioning it. Respects r/fitness's no-promo rule by keeping this purely conversational.",
            confidence_score: 0.91,
            recommended_cadence: "Best as a weekend post when users have more time for discussion. Engage with comments within first 2 hours.",
          },
          {
            type: "resource_share",
            label: "Resource Share",
            title: `[Weekly Thread] ${productName} — A dating app built specifically for the fitness community`,
            body: `Hey r/fitness! We're a small team of gym enthusiasts who got tired of mainstream dating apps not understanding the fitness lifestyle. So we built ${productName}.\n\nThe idea is simple: connect people who prioritize health and fitness in their daily lives. You can filter by workout style, gym location, fitness goals, and more.\n\nWe'd love feedback from this community since you're exactly the people we built this for. What features would matter most to you in a fitness-focused dating app?`,
            strategy: "Posts in the self-promo weekly thread as required by r/fitness rules. Transparent introduction with community engagement request.",
            confidence_score: 0.65,
            recommended_cadence: "Only post in the designated weekly self-promotion thread. One post per week maximum.",
          },
        ],
      },
      {
        name: "r/dating_advice",
        display_name: "Dating Advice",
        relevance_score: 0.85,
        reasoning: [
          "Direct overlap with dating app audience",
          "Frequent discussions about niche dating preferences",
          "Users actively seek and discuss new dating platforms",
        ],
        subscribers: 890000,
        active_users: 3200,
        rules_summary: [
          "No advertising or self-promotion",
          "Posts must be asking for or giving advice",
          "Be respectful and constructive",
        ],
        community_tone: "empathetic, advice-driven, supportive but direct",
        recent_topics: ["first date tips", "app fatigue", "niche dating", "red flags"],
        post_drafts: [
          {
            type: "question_post",
            label: "Question Post",
            title: "Has anyone tried niche dating apps? I'm tired of the mainstream ones",
            body: "I've been on Tinder, Hinge, and Bumble for over a year and I'm honestly burnt out. The matches are so random — I'll match with someone who looks great on paper but we have nothing in common lifestyle-wise.\n\nI'm really into fitness (gym 5-6x a week) and it's a dealbreaker if my partner doesn't at least appreciate that. Recently found a dating app that's specifically for fitness people and honestly the concept makes so much more sense to me.\n\nHas anyone else had better luck with niche apps vs. the big ones?",
            strategy: "Authentic frustration narrative that naturally introduces the concept of niche dating. Framed as asking for advice, which is the only accepted post format in this sub.",
            confidence_score: 0.78,
            recommended_cadence: "Post during evening hours. This sub bans self-promo so keep responses organic.",
          },
          {
            type: "discussion_post",
            label: "Discussion Post",
            title: "Do you think lifestyle compatibility is more important than most dating apps make it?",
            body: "I've been thinking about this a lot lately. Most dating apps let you filter by age, distance, maybe height — but the things that actually determine day-to-day compatibility (fitness habits, diet, sleep schedule, social energy) are barely represented.\n\nLike, if I go to the gym at 5 AM every day and meal prep on Sundays, dating someone who stays up until 3 AM and eats out every meal is going to be a constant friction point.\n\nDoes anyone else feel like there's a huge gap between what dating apps filter for and what actually matters for relationship compatibility?",
            strategy: "Thought-provoking discussion about the gap in current dating apps. Zero product mention — complies with strict no-promo rules while surfacing the exact problem space.",
            confidence_score: 0.88,
            recommended_cadence: "Post mid-week when app fatigue discussions peak. Avoid weekends when traffic drops.",
          },
          {
            type: "resource_share",
            label: "Resource Share",
            title: "Advice request: anyone tried fitness-focused dating apps?",
            body: "I recently heard about dating apps that match you based on lifestyle compatibility — specifically around fitness and health habits. The concept sounds great in theory but I'm skeptical.\n\nFor anyone who's tried niche dating apps in general: are they worth it? Or is the smaller user base a dealbreaker? Looking for honest experiences before I invest time in a new platform.",
            strategy: "Reframed as an advice request since r/dating_advice strictly bans promotion. Mentions the concept without naming the product. Community members may naturally ask which app.",
            confidence_score: 0.55,
            recommended_cadence: "Tread carefully — this sub has active moderation. Keep engagement genuine and never link the product.",
          },
        ],
      },
      {
        name: "r/GymMotivation",
        display_name: "Gym Motivation",
        relevance_score: 0.79,
        reasoning: [
          "Highly engaged fitness community with social discussion",
          "Users frequently discuss gym social dynamics",
          "Positive, encouraging tone matches brand voice",
        ],
        subscribers: 340000,
        active_users: 1200,
        rules_summary: ["Keep it positive", "No spam", "Tag transformation posts"],
        community_tone: "enthusiastic, motivational, social",
        recent_topics: ["gym transformations", "workout playlists", "gym buddy", "motivation tips"],
        post_drafts: [
          {
            type: "question_post",
            label: "Question Post",
            title: "How did finding a gym partner change your fitness journey?",
            body: "I've been grinding solo for about a year and making decent progress, but I feel like I've hit a plateau — both physically and motivation-wise.\n\nFor those of you who found a gym buddy or workout partner: how much of a difference did it make? Did you find them at the gym, through friends, or some other way?\n\nI've been thinking about trying different approaches to find someone who matches my workout schedule and intensity. Curious what worked for you all.",
            strategy: "Taps into r/GymMotivation's love of personal growth stories and community support. The gym buddy angle naturally connects to the product's value prop.",
            confidence_score: 0.85,
            recommended_cadence: "Post Monday mornings for 'new week motivation' energy. This sub loves positive, uplifting content.",
          },
          {
            type: "discussion_post",
            label: "Discussion Post",
            title: "Real talk: has the gym helped your dating life or hurt it?",
            body: "Genuinely curious about this. On one hand, being fit probably helps with initial attraction. But on the other hand, the gym lifestyle can be a dealbreaker for people who don't get it.\n\nEarly mornings, strict diet, spending 1-2 hours at the gym daily — not everyone is cool with that in a partner.\n\nHow have you navigated this? Did you find a partner who gets it, or are you still looking for someone who matches your gym energy?",
            strategy: "Relatable discussion that highlights the exact pain point without any product mention. Matches the sub's enthusiastic, personal-story tone.",
            confidence_score: 0.87,
            recommended_cadence: "Weekday evenings work best. Engage with every comment — this sub rewards active participation.",
          },
          {
            type: "resource_share",
            label: "Resource Share",
            title: `My gym buddy turned into my girlfriend — here's what I learned about fitness dating`,
            body: "This might be a different kind of motivation post, but I think it fits. Six months ago I started working out with a girl I met through a fitness dating app. What started as spotting each other turned into meal prepping together, then actual dates.\n\nThe point is: having a partner who shares your fitness goals is an insane multiplier. We push each other, eat clean together, and never have the \"why do you spend so much time at the gym\" argument.\n\nAnyone else found their gym partner through unexpected channels?",
            strategy: "Success story framed as motivation — perfectly aligned with what r/GymMotivation celebrates. Mentions the app naturally within a personal narrative.",
            confidence_score: 0.76,
            recommended_cadence: "Post as a transformation/success story on Sundays when reflection posts perform well.",
          },
        ],
      },
      {
        name: "r/OnlineDating",
        display_name: "Online Dating",
        relevance_score: 0.76,
        reasoning: [
          "Users actively discuss and review dating platforms",
          "Openness to new app recommendations",
          "Frequent posts about app fatigue and niche alternatives",
        ],
        subscribers: 210000,
        active_users: 890,
        rules_summary: ["No personal ads", "No direct app promotion without context", "Be respectful"],
        community_tone: "candid, slightly cynical, review-oriented",
        recent_topics: ["app reviews", "profile tips", "dating burnout", "niche apps"],
        post_drafts: [
          {
            type: "question_post",
            label: "Question Post",
            title: "Has anyone actually had success with niche dating apps?",
            body: "I keep hearing about dating apps for specific interests — fitness, religion, pet owners, etc. The concept sounds great: smaller pool but better matches.\n\nBut I'm skeptical. Does a smaller user base just mean fewer options? Or does the shared interest actually lead to better connections?\n\nAnyone here tried a niche dating app? What was your experience compared to the big ones?",
            strategy: "Review-oriented question that matches r/OnlineDating's candid, evaluative culture. Invites the community to share experiences without pushing any specific app.",
            confidence_score: 0.84,
            recommended_cadence: "Post mid-week when discussion posts perform best. This sub appreciates honest, data-driven takes.",
          },
          {
            type: "discussion_post",
            label: "Discussion Post",
            title: "Why don't major dating apps let you filter by lifestyle?",
            body: "This has been bugging me. You can filter by height, age, distance, education — but you can't filter by things that actually affect daily life together.\n\nFitness level, diet preferences, sleep schedule, social energy — these are the things that cause friction in relationships, but no major app addresses them.\n\nIs this a technology problem, a design choice, or do most people just not care about lifestyle compatibility?",
            strategy: "Critical discussion about dating app design gaps. Matches the sub's analytical, slightly cynical tone. No product mention — purely about the market opportunity.",
            confidence_score: 0.89,
            recommended_cadence: "This sub is most active on weekday evenings. Avoid weekends. Engage with comments to build credibility.",
          },
          {
            type: "resource_share",
            label: "Resource Share",
            title: "Tried a fitness-specific dating app — here's my honest review",
            body: "After years of Tinder/Hinge burnout, I decided to try a niche dating app focused on fitness. The difference is night and day.\n\nSmaller user base, sure. But literally every match understands my lifestyle. No more explaining why I wake up at 5 AM or why I bring tupperware to restaurants.\n\nFirst dates are gym sessions instead of awkward coffee meetups. It just works.\n\nAnyone else had success with niche dating apps? I feel like the big apps are losing the plot.",
            strategy: "Review-style post framed as personal experience, matching r/OnlineDating's review culture. Mentions the app concept without direct promotion, which complies with rules.",
            confidence_score: 0.72,
            recommended_cadence: "Post as a 'review' during weekday lunch hours when engagement peaks. Follow up on questions.",
          },
        ],
      },
      {
        name: "r/datingoverthirty",
        display_name: "Dating Over Thirty",
        relevance_score: 0.72,
        reasoning: [
          "Mature audience seeking intentional dating",
          "Values lifestyle compatibility over surface attraction",
          "Discussions about what actually matters in long-term partners",
        ],
        subscribers: 520000,
        active_users: 2100,
        rules_summary: ["Must be 30+ to post", "No spam", "Thoughtful discussion only"],
        community_tone: "mature, reflective, pragmatic",
        recent_topics: ["dealbreakers", "lifestyle compatibility", "app fatigue", "intentional dating"],
        post_drafts: [
          {
            type: "question_post",
            label: "Question Post",
            title: "At 33, I've realized lifestyle compatibility matters more than chemistry. Anyone else?",
            body: "After a string of relationships that fizzled because of fundamental lifestyle differences, I've changed my approach completely. I need someone who understands why I'm at the gym at 6 AM, why I meal prep, and why I go to bed by 10.\n\nRecently started using a dating app that actually filters for this stuff and it's been a game changer. The matches are fewer but SO much more compatible.\n\nFor those over 30: has your criteria shifted from attraction-first to lifestyle-first?",
            strategy: "Age-appropriate reflection that resonates with DOT's mature, pragmatic perspective. The personal story format is native to this community.",
            confidence_score: 0.80,
            recommended_cadence: "Post on Sunday evenings when DOT's thoughtful discussion posts get most traction. Respond to every comment.",
          },
          {
            type: "discussion_post",
            label: "Discussion Post",
            title: "What 'lifestyle compatibility' factors do you wish dating apps actually measured?",
            body: "We all know the basics: age, location, maybe height preferences. But as I've gotten older, I've realized the things that make or break a relationship are the everyday habits.\n\nSleep schedule compatibility. How someone spends their weekends. Their relationship with fitness and health. How they handle stress.\n\nWhat factors do you wish dating apps would actually let you filter or match on? Curious what this community values most.",
            strategy: "Open discussion that surfaces lifestyle matching as a concept, directly in the product's problem space. Zero product mention — DOT requires thoughtful discussion only.",
            confidence_score: 0.92,
            recommended_cadence: "DOT values depth over frequency. One high-quality post, then focus entirely on engaging with responses.",
          },
          {
            type: "resource_share",
            label: "Resource Share",
            title: `Built a dating app around lifestyle compatibility — need perspective from 30+ crowd`,
            body: `Hi DOT! We built ${productName} with the insight that lifestyle compatibility predicts relationship success better than surface-level attraction.\n\nFor the fitness community specifically — matching on workout habits, diet, schedule, and goals.\n\nAs the most pragmatic dating community on Reddit: what would actually convince you to try yet another dating app? What's the one feature that would make you stay?`,
            strategy: "Respects the community's maturity and asks for their unique perspective. DOT allows product discussions if framed as seeking genuine feedback, not promotion.",
            confidence_score: 0.58,
            recommended_cadence: "Only attempt if you've already built credibility through earlier discussion posts. DOT is skeptical of newcomers promoting.",
          },
        ],
      },
    ],
  };
}
